
/* This file was generated by idltool 53.6. Do not edit */

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_CHIPSET_H
#include <libraries/chipset.h>
#endif

extern ULONG                VARARGS68K _chipset_Obtain(struct chipsetIFace *);
extern ULONG                VARARGS68K _chipset_Release(struct chipsetIFace *);
extern char *               VARARGS68K _chipset_allocChip(struct chipsetIFace *, uint32_t size);
extern void                 VARARGS68K _chipset_freeChip(struct chipsetIFace *, void * mem);
extern void *               VARARGS68K _chipset_hostAddressToChip(struct chipsetIFace *, void * adr);
extern void                 VARARGS68K _chipset_chipAddressToHost(struct chipsetIFace *, void * adr);
extern void                 VARARGS68K _chipset_writeChip(struct chipsetIFace *, ULONG offset, ULONG value);
extern ULONG                VARARGS68K _chipset_readChip(struct chipsetIFace *, ULONG offset);
