
INC = -I../ -I./ -Itests/



do = tests/mem.c \
	tests/cia.c \
	tests/cia2.c

OBJS = $(do:.c=.exe)

all:	$(OBJS)
	@echo $(OBJS)

%.exe: %.c
	$(CC) $(LINK) $(INC)  $(@:.exe=.c) -o $@

%.o:		%.c 
	gcc  -Wall -O3  $(INC) -c  -D__USE_INLINE__ -D__no_stdlib__ $(@:.o=.c) -o $@

uade/cia.o:		uade/cia.c 
	gcc  -Wall -O3  $(INC) $(OPT) -c  -D__USE_INLINE__ -D__no_stdlib__ $(@:.o=.c) -o $@

tests/mem.exe: micro_sys/memory.o tests/mem.c
	$(CC) $(LINK) $(INC) micro_sys/memory.o $(@:.exe=.c) -o $@

tests/cia.exe: uade/cia.o tests/cia.c
	$(CC) $(LINK) $(INC) uade/cia.o $(@:.exe=.c) -o $@

tests/cia2.exe: uade/cia.o timer_device.o tests/cia2.c
	$(CC) $(LINK) $(INC) uade/cia.o timer_device.o $(@:.exe=.c) -o $@

clean:
	delete tests/#?.exe

