/*
**	$Id$
**	Generated by IDLTool 53.6
**	Do not edit
**
**	AutoInit stub for chipset
**
**	Copyright (c) 2010 LiveForIt Software.
**	GPL2 License..
*/

#include <exec/types.h>
#include <libraries/chipset.h>

#include <interfaces/chipset.h>
#include <proto/exec.h>
#include <assert.h>

/****************************************************************************/

struct Library * chipsetBase = NULL;
static struct Library * __chipsetBase;

/****************************************************************************/

void chipset_base_constructor(void)
{
    if (chipsetBase != NULL)
    {
        return; /* Someone was quicker, e.g. an interface constructor */
    }
    __chipsetBase = chipsetBase = (struct Library *)IExec->OpenLibrary("chipset.library", 0L);
    assert(chipsetBase != NULL);
}
__attribute__((section(".ctors.zzzz"))) static void
(*chipset_base_constructor_ptr)(void) USED = chipset_base_constructor;

/****************************************************************************/

void chipset_base_destructor(void)
{
    if (__chipsetBase)
    {
        IExec->CloseLibrary((struct Library *)__chipsetBase);
    }
}
__attribute__((section(".dtors.zzzz"))) static void
(*chipset_base_destructor_ptr)(void) USED = chipset_base_destructor;

/****************************************************************************/

