
/* This file was generated by idltool 53.6. Do not edit */

#include "chipset_vectors.h"

STATIC CONST APTR main_v1_vectors[] =
{
    _chipset_Obtain,
    _chipset_Release,
    NULL,
    NULL,
    _chipset_allocChip,
    _chipset_freeChip,
    _chipset_hostAddressToChip,
    _chipset_chipAddressToHost,
    _chipset_writeChipLong,
    _chipset_writeChipWord,
    _chipset_writeChipByte,
    _chipset_readChipLong,
    _chipset_readChipWord,
    _chipset_readChipByte,
    (APTR)-1
};

