
/* This file was generated by idltool 53.6. Do not edit */

#include "chipset_vectors.h"

STATIC CONST APTR main_v1_vectors[] =
{
    _chipset_Obtain,
    _chipset_Release,
    NULL,
    NULL,
    _chipset_allocChip,
    _chipset_freeChip,
    _chipset_hostAddressToChip,
    _chipset_chipAddressToHost,
    _chipset_writeChip,
    _chipset_readChip,
    (APTR)-1
};

