
/* This file was generated by idltool 53.6. Do not edit */

#include "chipset_vectors.h"

STATIC CONST APTR main_v1_vectors[] =
{
    _chipset_Obtain,
    _chipset_Release,
    NULL,
    NULL,
    _chipset_allocChip,
    _chipset_freeChip,
    _chipset_hostAddressToChip,
    _chipset_chipAddressToHost,
    _chipset_writeChipLong,
    _chipset_writeChipWord,
    _chipset_writeChipByte,
    _chipset_readChipLong,
    _chipset_readChipWord,
    _chipset_readChipByte,
    _chipset_bitChgChipLong,
    _chipset_bitChgChipWord,
    _chipset_bitChgChipByte,
    _chipset_bitSetChipLong,
    _chipset_bitSetChipWord,
    _chipset_bitSetChipByte,
    _chipset_bitClrChipLong,
    _chipset_bitClrChipWord,
    _chipset_bitClrChipByte,
    _chipset_setCIATimingAccuracy,
    _chipset_spyCIAA,
    _chipset_spyCIAB,
    _chipset_setCIAClockSpeed,
    _chipset_chipOwnBlitter,
    _chipset_chipDisownBlitter,
    _chipset_chipWaitBlit,
    (APTR)-1
};

