#ifndef INLINE4_CHIPSET_H
#define INLINE4_CHIPSET_H

/*
** This file was auto generated by idltool 53.6.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_CHIPSET_H
#include <libraries/chipset.h>
#endif
#include <interfaces/chipset.h>

/* Inline macros for Interface "main" */
#define allocChip(size) Ichipset->allocChip((size)) 
#define freeChip(mem) Ichipset->freeChip((mem)) 
#define hostAddressToChip(adr) Ichipset->hostAddressToChip((adr)) 
#define chipAddressToHost(adr) Ichipset->chipAddressToHost((adr)) 
#define writeChip(offset, value) Ichipset->writeChip((offset), (value)) 
#define readChip(offset) Ichipset->readChip((offset)) 

#endif /* INLINE4_CHIPSET_H */
